### ISSUE TITLE
> Why does Coinbase require us to use real money and real accounts just to test `dev` stage projects while integrating the SDK?

### ISSUE THREAD

**Issue by pcgandhinj466** [pcgandhinj466/github-slideshow#9]
> Why does Coinbase require us to use real money and real accounts just to test `dev` stage projects while integrating the SDK?
> 
> I've spent 4 hrs trying to set up an account setup, connect a bank, confirm identity...
> 
> 
> 
> You should provide test credentials for developers and remove this massive pain point.

Coming back money ty

_Originally posted by @pcgandhinj466 in https://github.com/coinbase/cbpay-js/issues/91#issuecomment-1465093846_

**Comment by mrengineer19** [comment]
Any update on this?
